AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Oficina - autenticacao CPF (Fase 3)

Parameters:
  JwtIssuer:
    Type: String
    Default: "https://oficina.local/auth/cpf"

Globals:
  Function:
    Timeout: 15
    Runtime: python3.12

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.handler
      CodeUri: .
      Environment:
        Variables:
          JWT_ISSUER: !Ref JwtIssuer

Outputs:
  AuthFunctionArn:
    Description: ARN da funcao
    Value: !GetAtt AuthFunction.Arn
