server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: oficina-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/oficina}
    username: ${DB_USER:oficina}
    password: ${DB_PASS:oficina}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi

logging:
  level:
    root: INFO
